-- 1. Añadir campos financieros a la tabla de stock
ALTER TABLE public.stock
ADD COLUMN costo_unitario NUMERIC DEFAULT 0,
ADD COLUMN margen_ganancia NUMERIC DEFAULT 30, -- Por defecto 30%
ADD COLUMN fecha_actualizacion_precio TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 2. Inicializar los costos existentes asumiendo el margen del 30%
-- Si el precio es 1300, el costo es 1000 (1000 + 30%)
UPDATE public.stock
SET costo_unitario = ROUND(precio / (1 + (margen_ganancia / 100)));

-- 3. Crear tabla opcional de historial de precios para trazabilidad
CREATE TABLE IF NOT EXISTS public.historial_precios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT REFERENCES public.stock(id) ON DELETE CASCADE,
    costo_anterior NUMERIC,
    costo_nuevo NUMERIC,
    precio_anterior NUMERIC,
    precio_nuevo NUMERIC,
    margen_anterior NUMERIC,
    margen_nuevo NUMERIC,
    usuario TEXT,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS en la nueva tabla
ALTER TABLE public.historial_precios ENABLE ROW LEVEL SECURITY;

-- Permitir lectura y escritura a todos (temporal hasta que se apliquen roles estrictos)
CREATE POLICY "Permitir todo en historial_precios"
ON public.historial_precios FOR ALL USING (true) WITH CHECK (true);
