-- ==========================================
-- SCHEMA FOR MERCADO DE CAFETERAS
-- ==========================================

-- 1. Table: repairs
CREATE TABLE IF NOT EXISTS public.repairs (
    id TEXT PRIMARY KEY, -- Manual ID (e.g., #031)
    created_at TIMESTAMPTZ DEFAULT NOW(),
    modelo TEXT NOT NULL,
    cliente TEXT NOT NULL,
    celular TEXT,
    problema TEXT,
    fecha TEXT, -- Original string format (dd/mm/yyyy)
    sucursal TEXT NOT NULL, -- Current location (e.g., 'lanus')
    sucursal_admit TEXT, -- Original admission branch
    estado TEXT DEFAULT 'recibido', -- recibido, progreso, listo, entregado
    prioridad TEXT DEFAULT 'media', -- baja, media, alta
    is_oster BOOLEAN DEFAULT FALSE,
    oster_op TEXT,
    diagnostico_tecnico TEXT,
    aprobado BOOLEAN DEFAULT FALSE,
    fecha_entrega TIMESTAMPTZ,
    presupuesto JSONB -- { componentes: [], manoObra: 0, total: 0 }
);

-- 2. Table: stock
CREATE TABLE IF NOT EXISTS public.stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    categoria TEXT,
    lanus INTEGER DEFAULT 0,
    belgrano INTEGER DEFAULT 0,
    deposito INTEGER DEFAULT 0,
    min INTEGER DEFAULT 5,
    precio NUMERIC DEFAULT 0,
    imagen TEXT
);

-- 3. Table: sales
CREATE TABLE IF NOT EXISTS public.sales (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    fecha TIMESTAMPTZ DEFAULT NOW(),
    fecha_str TEXT, -- for legacy compatibility (dd/mm)
    producto TEXT NOT NULL,
    qty INTEGER NOT NULL,
    total NUMERIC NOT NULL,
    sucursal TEXT NOT NULL,
    medio_pago TEXT
);

-- 4. Table: transfers
CREATE TABLE IF NOT EXISTS public.transfers (
    id TEXT PRIMARY KEY, -- Manual ID (e.g., TR-101)
    origen TEXT NOT NULL,
    destino TEXT NOT NULL,
    producto TEXT NOT NULL,
    stock_id BIGINT,
    qty INTEGER NOT NULL,
    fecha TEXT,
    estado TEXT DEFAULT 'enviado' -- enviado, recibido
);

-- 5. Enable Row Level Security (RLS) - Optional but recommended
ALTER TABLE public.repairs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.transfers DISABLE ROW LEVEL SECURITY;

-- 6. Initial Data Migration (Seed con productos reales)
-- Limpiamos stock previo
TRUNCATE public.stock RESTART IDENTITY;

INSERT INTO public.stock (nombre, precio, categoria, lanus, belgrano, deposito, min, imagen) VALUES
('Café Colombia Guanes 1 kilo - Bertone', 75000.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/2f0788654b387c61d17c96c71146594185a623c2d43e2a8ebfcea40f8ba61144285824.jpg'),
('Café Colombia Guanes 500gr - Bertone', 39500.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/2a433862bbb7f32ca8e5e63f4bb5e0766149826779e315266b1540618a7e8fc8285824.jpg'),
('Café Colombia Guanes 250gr - Bertone', 22000.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/d91091a931315601e74b8767492cc88cb29b83454670384c17f49522c0e18032285824.jpg'),
('Café Brasil Pedra azul 1 kilo - Bertone', 70500.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/da90152e60af38c4cf15a778663bc9a9f920bd15d699110cbc833ddd3628fcdb285824.jpg'),
('Café Brasil Pedra azul 500gr - Bertone', 37000.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/bbf1ce643b1cbee69f6cc6f4bf7c58465f4080a204034af13be67601b05c5e1f285824.jpg'),
('Café Brasil Pedra azul 250gr - Bertone', 20500.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/1f667a03cea8f4a10b5641e59392fd0d2c8029d30b54c9c0080c5063a04a933e285824.jpg'),
('Café Brasil Bourbon Rojo 1kilo - Bertone', 66500.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/bde378e61a8c71966ca259bb6a102c2ae88cde935c0f71e0af392b677afc6d98285824.jpg'),
('Café Brasil Bourbon Rojo 500gr - Bertone', 36600.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/b523e10a22e7a98fb097990a1556b937c20b058ade9e1bc8420ba49f107bd2ce285824.jpg'),
('Café Brasil Bourbon Rojo 250gr - Bertone', 19600.00, 'Café > Especialidad', 10, 10, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/2e27e04b244fd60c26d775b4490d704e0d4516982f55a52e1ffb312ba3a1e441285824.jpg'),
('Intensidad Suave Cápsulas p/ Nespresso', 7500.00, 'Cápsulas', 0, 0, 0, 5, 'https://d22fxaf9t8d39k.cloudfront.net/6b51698cb55eb6db5dce29fc7ef1e4e3aeb2f9df2219eee13d965af0ba7a5ff7285824.jpg'),
('Intensidad Intermedio Cápsulas p/ Nespresso', 9100.00, 'Cápsulas', 15, 10, 50, 5, 'https://d22fxaf9t8d39k.cloudfront.net/e11f08fc2053479690155f0e083d1f31d690efbb58b4afe59d1a16840be2d2bb285824.jpg'),
('Intensidad Fuerte Cápsulas p/ Nespresso', 9100.00, 'Cápsulas', 15, 10, 50, 5, 'https://d22fxaf9t8d39k.cloudfront.net/b26e9ccc5943df3d136f443d433407d0b8830e7da0ff3cc19082a4cc45b3e9e7285824.jpg'),
('Cafetera Moka Express 2 tz - Bialetti', 108900.00, 'Cafeteras Moka', 5, 2, 10, 2, 'https://d22fxaf9t8d39k.cloudfront.net/e84eb9e41e66f437e2e4e6675e5f1fd3680485ce665ba66515e5361e921e8657285824.jpg'),
('Cafetera Moka Express 3tz - Bialetti', 114400.00, 'Cafeteras Moka', 5, 2, 10, 2, 'https://d22fxaf9t8d39k.cloudfront.net/60a844ee131c1f30bfbe427bb511e3f351ca27840e9628845fcebd98fb22cedf285824.jpg'),
('Cafeteras Moka Express 4tz - Bialetti', 143000.00, 'Cafeteras Moka', 5, 2, 10, 2, 'https://d22fxaf9t8d39k.cloudfront.net/08b56c4041067f02b22c12a68d9ba722bc6029e0fb835a4a74f8813ed62ec019285824.jpg'),
('Cafetera Moka Express 6tz - Bialetti', 161000.00, 'Cafeteras Moka', 5, 2, 10, 2, 'https://d22fxaf9t8d39k.cloudfront.net/bd697de83666f104b955827e4640ae984e995ecc1b78b485b05a1fb6fdbace10285824.jpg'),
('Cafetera Moka Express 9tz - Bialetti', 236900.00, 'Cafeteras Moka', 2, 1, 5, 2, 'https://d22fxaf9t8d39k.cloudfront.net/26704ed6533d74df5c1e3f442a1c1e3b593588885a97b0ecee82784efd71ac1e285824.jpg'),
('Cafetera Moka Express 12tz - Bialetti', 307100.00, 'Cafeteras Moka', 2, 1, 5, 2, 'https://d22fxaf9t8d39k.cloudfront.net/12189adc0043f53b4cdd75e5792b99ce59741efe9ab8abadcc053cbe23238e12285824.jpg'),
('Cafetera Moka Mini Express Kandinsky 2tz', 215100.00, 'Cafeteras Moka', 3, 1, 5, 2, 'https://d22fxaf9t8d39k.cloudfront.net/a99cbc528a3a7ff78f311dbf0b535abcd0b70c2c31832919504c32cc14a58e8c285824.jpg'),
('Cafetera Moka Brikka Express 4tz', 237000.00, 'Cafeteras Moka', 2, 2, 10, 2, 'https://d22fxaf9t8d39k.cloudfront.net/e8d75f667027196668cc2a9f2ae1bc8f04e735dbcad61ceb5561ce49618d4c1c285824.png'),
('Prensa francesa 1L - Domestic', 33000.00, 'Prensa Francesa', 8, 4, 15, 3, 'https://d22fxaf9t8d39k.cloudfront.net/95d29f0ef046250c3b3e151e976943001f7cbca165ce3cd815c580b744561ebf285824.jpg'),
('Descalcificante en polvo', 7000.00, 'Limpieza', 20, 15, 60, 10, 'https://d22fxaf9t8d39k.cloudfront.net/53c2b87a73c7d7d25a9ff50995ec157482d6da04b99b3027f8f75a508f4685dd285824.jpg'),
('Main Fusion - Jarabe de Avellanas', 18200.00, 'Insumos', 12, 8, 30, 5, 'https://d22fxaf9t8d39k.cloudfront.net/f3ea335f68531839c8ea46a263e1630cae8036ccbea26b9be74afbc01b14fa41285824.png'),
('Main Fusion - Jarabe de Amaretto', 25600.00, 'Insumos', 5, 5, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/2d650b7fd1dbfe53d6b96f862165cf324a66b068a3d03177b8ff8889d95edea8285824.png'),
('Portafiltro N 2 - Domestic', 6200.00, 'Insumos', 25, 20, 50, 10, 'https://d22fxaf9t8d39k.cloudfront.net/bfefd22c82cdd024bb0def5fae125538806bdd2fc17f570d9dfc972c33f11dd0285824.webp'),
('Portafiltro Nro 4 - Domestic', 6400.00, 'Insumos', 25, 20, 50, 10, 'https://d22fxaf9t8d39k.cloudfront.net/fd8a005e4ec88baf6933e019bc2a1e5df57665f889ec205856fe87c3ee544c5c285824.webp'),
('Filtros de Papel N 2 x 30un - Domestic', 4700.00, 'Insumos', 40, 30, 80, 20, 'https://d22fxaf9t8d39k.cloudfront.net/415ea99a52927e9121f08a0b607fb433de92a3d97d1f7199738d4d2cf64174a3285824.jpg'),
('Filtros de Papel N 4 x 30un - Domestic', 4950.00, 'Insumos', 40, 30, 80, 20, 'https://d22fxaf9t8d39k.cloudfront.net/7829c93c565ea079124f7fd80017703132f6393df70a73334d19b7dd320cd7a4285824.jpg'),
('Jarra Acero Inox Crystal Rock 600ML', 24000.00, 'Accesorios', 10, 5, 20, 5, 'https://d22fxaf9t8d39k.cloudfront.net/ebab8d2d206920966aac03d9f91e52b8b9a6ec3a4f209de66cd87a346c619063285824.jpg'),
('Mini Batidor Espumador', 7000.00, 'Accesorios', 30, 20, 100, 10, 'https://d22fxaf9t8d39k.cloudfront.net/7f4d1b4d4c54d5290f523696306cd46d9f11b4a08384dec24517f02cdcab90e1285824.png'),
('Capsulas Recargables Nespresso Caffettino', 15200.00, 'Cápsulas', 15, 10, 30, 5, 'https://d22fxaf9t8d39k.cloudfront.net/8a91480393b1f8fd29f188ca7ed53840ab777b4799b9ab7b80b18019cc2b237b285824.png');
