-- ==========================================
-- SCRIPT DE CORRECCIÓN — Mercado de Cafeteras
-- Ejecutar en Supabase SQL Editor
-- ==========================================

-- 1. DESHABILITAR RLS en todas las tablas (para usar con anon key)
ALTER TABLE public.repairs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.transfers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_shifts DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.cash_withdrawals DISABLE ROW LEVEL SECURITY;

-- 2. Eliminar políticas existentes que puedan bloquear inserts
DO $$
DECLARE
    pol RECORD;
BEGIN
    FOR pol IN 
        SELECT policyname, tablename 
        FROM pg_policies 
        WHERE schemaname = 'public'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', pol.policyname, pol.tablename);
    END LOOP;
END $$;

-- 3. Verificar que la tabla repairs tiene todas las columnas necesarias
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS sucursal_admit TEXT;
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS is_oster BOOLEAN DEFAULT FALSE;
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS is_peabody BOOLEAN DEFAULT FALSE;
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS oster_op TEXT DEFAULT '';
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS peabody_op TEXT DEFAULT '';
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS cliente_email TEXT DEFAULT '';
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS diagnostico_tecnico TEXT DEFAULT '';
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS aprobado BOOLEAN DEFAULT FALSE;
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS fecha_entrega TIMESTAMPTZ;
ALTER TABLE public.repairs ADD COLUMN IF NOT EXISTS presupuesto JSONB;

-- 4. Verificar tabla transfers
ALTER TABLE public.transfers ADD COLUMN IF NOT EXISTS stock_id BIGINT;

-- 5. Verificar tabla audit_logs (puede que no exista)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    usuario TEXT,
    rol TEXT,
    sucursal TEXT,
    accion TEXT NOT NULL,
    detalles TEXT
);
ALTER TABLE public.audit_logs DISABLE ROW LEVEL SECURITY;

-- 6. Verificar tabla cash_shifts
CREATE TABLE IF NOT EXISTS public.cash_shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sucursal TEXT NOT NULL,
    estado TEXT DEFAULT 'abierta',
    abierto_por TEXT,
    monto_inicial NUMERIC DEFAULT 0,
    monto_final NUMERIC,
    cerrado_por TEXT,
    opened_at TIMESTAMPTZ DEFAULT NOW(),
    closed_at TIMESTAMPTZ,
    notas TEXT
);
ALTER TABLE public.cash_shifts DISABLE ROW LEVEL SECURITY;

-- 7. Asegurar columna categoria en cash_withdrawals
ALTER TABLE public.cash_withdrawals ADD COLUMN IF NOT EXISTS categoria TEXT DEFAULT 'Gasto Local';

-- 8. Grant permisos completos al rol anon (necesario para que funcione sin autenticación)
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT USAGE ON SCHEMA public TO anon;

-- 9. Verificar estructura de repairs con SELECT
SELECT column_name, data_type, is_nullable 
FROM information_schema.columns 
WHERE table_schema = 'public' AND table_name = 'repairs'
ORDER BY ordinal_position;

-- 10. Verificar que no hay datos corruptos en repairs
SELECT id, estado, sucursal, sucursal_admit FROM public.repairs ORDER BY created_at DESC LIMIT 20;
