-- Tabla para registrar retiros de caja
CREATE TABLE IF NOT EXISTS public.cash_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto NUMERIC NOT NULL,
    motivo TEXT NOT NULL,
    sucursal TEXT NOT NULL,
    usuario TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.cash_withdrawals ENABLE ROW LEVEL SECURITY;

-- Permitir acceso temporal (hasta configurar roles estrictos)
CREATE POLICY "Permitir todo en cash_withdrawals"
ON public.cash_withdrawals FOR ALL USING (true) WITH CHECK (true);
